{
 "title": "Application Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Bags/Flights Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Records Produced",
   "type": "timeseries",
   "description": "The number of bag and flight records produced",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "produced_test_flights_total", "legendFormat": "Flights" },
    { "expr": "produced_test_bags_total", "legendFormat": "Bags" }
   ]
  },
  {
   "title": "Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(produced_test_flights_total[1m])",
     "legendFormat": "Flights/sec"
    },
    {
     "expr": "rate(produced_test_bags_total[1m])",
     "legendFormat": "Bags/sec"
    }
   ]
  },
  {
   "title": "Latest Produced Flight Arrival",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "expr": "latest_produced_flight_arrival_timestamp * 1000",
     "legendFormat": "Latest Flight"
    }
   ]
  },
  { "title": "Bags/Flights Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Records Consumed",
   "type": "timeseries",
   "description": "The number of flight and bag records consumed",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "processed_flights_total", "legendFormat": "Flights" },
    { "expr": "processed_bags_total", "legendFormat": "Bags" }
   ]
  },
  {
   "title": "Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(processed_flights_total[1m])",
     "legendFormat": "Flights/sec"
    },
    { "expr": "rate(processed_bags_total[1m])", "legendFormat": "Bags/sec" }
   ]
  },
  {
   "title": "Latest Consumed Flight Arrival",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "expr": "latest_consumed_flight_arrival_timestamp * 1000",
     "legendFormat": "Latest Flight"
    }
   ]
  },
  { "title": "Database Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Stored Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_stored_flights_total", "legendFormat": "Stored Flights" },
    { "expr": "redis_stored_bags_total", "legendFormat": "Stored Bags" }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "Memory Used" }
   ]
  },
  { "title": "FlightArrivalWork Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Work Items Produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "produced_arriving_flight_work_total",
     "legendFormat": "Work Items"
    }
   ]
  },
  {
   "title": "Work Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(produced_arriving_flight_work_total[1m])",
     "legendFormat": "Work Items/sec"
    }
   ]
  },
  {
   "title": "Latest Work Item Arrival",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "latest_work_arrival_timestamp * 1000",
     "legendFormat": "Latest Work Item"
    }
   ]
  }
 ]
}